name: GitHub Streak Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DenverCoder1/github-readme-streak-stats@main
        with:
          token: ${{ secrets.TOKEN }}
          path: streak-stats.svg
          options: "user=ggtxz&theme=vue-dark&hide_border=true"

      - uses: EndBug/add-and-commit@v9
        with:
          add: streak-stats.svg
          message: "chore: update streak stats"
